apiVersion: v1
kind: Service
metadata:
  name: clerk-app-service
  labels:
    app: clerk-app
spec:
  type: NodePort 
  selector:
    app: clerk-app
  ports:
    - protocol: TCP
      port: 3000         
      targetPort: 3000 
      nodePort: 32703