apiVersion: v1
kind: Secret
metadata:
  name: clerk-api-secrets
type: Opaque
data:
  CLERK_PUBLIC_KEY: ejMwMldxZWZmZmRadlcwUXIyQkZienl1eVM2UDl4dXQK
  CLERK_PRIVATE_KEY: QThHclNuVVBaZTdTdWlKYkRvMHd2ZnJJc0VHT0tncUUK