replicaCount: 2

image:
  repository: 702551696126.dkr.ecr.eu-central-1.amazonaws.com/dev-cluster-1-app-img
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

env:
  BASE_URL: "https://clerk.johnydev.com"
