apiVersion: v1
kind: Service
metadata:
  name: clerk-app-service
  namespace: dev-clerk-app
  labels:
    app: clerk-app
spec:
  type: LoadBalancer 
  selector:
    app: clerk-app
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 3000 