apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clerk-app-secrets
  namespace: dev-clerk-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: clerk-k8s-secrets
    creationPolicy: Owner
  data:
    - secretKey: CLERK_PUBLIC_KEY
      remoteRef:
        key: clerk-app-secrets-v3
        property: CLERK_PUBLIC_KEY
    - secretKey: CLERK_PRIVATE_KEY
      remoteRef:
        key: clerk-app-secrets-v3
        property: CLERK_PRIVATE_KEY
    - secretKey: CLERK_API_URL
      remoteRef:
        key: clerk-app-secrets-v3
        property: CLERK_API_URL